### ISSUE TITLE
Cert based Authentication

### ISSUE THREAD

**Issue by wahmedswl** [kestra-io/plugin-mqtt#25]
### Feature description

Hi!
Is cert based auth supported? AWS mqtt broker uses cert based auth, is that a supported scenario?

Thanks

**Comment by anna-geller** [comment]
I'm really sorry for responding so late, it seems it is supported: https://kestra.io/plugins/tasks/io.kestra.plugin.mqtt.publish#httpshostnameverificationenabled

![image](https://github.com/kestra-io/plugin-mqtt/assets/86264395/e9de50b0-de09-448b-bff8-d554afb59ccf)

please ping us via Slack if you still struggle to set this up and we'll reopen te issue and investigate a fix
